[workspace]
authors = ["Sébastien Boisgérault <Sebastien.Boisgerault@gmail.com>"]
channels = ["conda-forge"]
name = "micropython"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[activation.env]
PATH = "$PIXI_PROJECT_ROOT/bin:$PATH"

[tasks.setup]
cmd = "sh install-micropython.sh"
outputs = ["bin/micropython"]

[tasks.main]
cmd = "micropython main.py"
depends-on = ["setup"]

[dependencies]
make = ">=4.4.1,<5"
c-compiler = ">=1.11.0,<2"
